<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Accumulators\" />
    <Folder Include="Savers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Algorithm\Base\BaseContract\BaseContract.csproj" />
    <ProjectReference Include="..\..\Data\BioAlgorithm.Data.Contract\BioAlgorithm.Data.Contract.csproj" />
    <ProjectReference Include="..\..\Data\BioAlgorithm.Data\BioAlgorithm.Data.csproj" />
  </ItemGroup>

</Project>
